// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockExchange.DataContext;

namespace StockExchange.Migrations
{
    [DbContext(typeof(SEContext))]
    [Migration("20201213134449_m1")]
    partial class m1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("StockExchange.Entities.Company", b =>
                {
                    b.Property<string>("CCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CEO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SEId")
                        .HasColumnType("int");

                    b.Property<double>("Turnover")
                        .HasColumnType("float");

                    b.HasKey("CCode");

                    b.HasIndex("SEId");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("StockExchange.Entities.StockExchanges", b =>
                {
                    b.Property<int>("SEId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SEName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SEId");

                    b.ToTable("StockExchanges");
                });

            modelBuilder.Entity("StockExchange.Entities.Company", b =>
                {
                    b.HasOne("StockExchange.Entities.StockExchanges", "se")
                        .WithMany()
                        .HasForeignKey("SEId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("se");
                });
#pragma warning restore 612, 618
        }
    }
}
